### PR TITLE
Get rid of deprecated react methods (#368)

### PR DESCRIPTION
**Pull request by skurnevich**
Fix for zowe/zlux#368.

Got rid of deprecated react methods componentWillReceiveProps and componentWillMount.
- **componentWillMount** has been replaced with **componentDidMount**
- **componentWillReceiveProps** updating state has been replaced with **getDerivedStateFromProps**
- **componentWillReceiveProps** invoking side functions or fetching the data has been replaced with **componentDidUpdate**

Also for _Editor.js_ I have removed **currentEtag** from state and used **props.etag** as it seems to be not mutated inside of component, please review this moment, I could be missing something.
Same for _EditorMenuBar.js_, **syntax** changing is happening in the parent component and coming back to menu bar in props. 

Thanks,
Sergei

### CODE REVIEW

**Comment by jordanCain** [comment]
@skurnevich We've had some issues with our build server unfortunately even the backup image can't be redeployed so all PRs are on hold, the failure you're seeing is for SonarCloud Code Analysis and having uncovered lines of new code, we took the decision to only track new code coverage to both actions and reducer files/functions but the Linux Foundation infrastructure that runs sonar cloud hasn't been updated to reflect this. 

So no changes should be needed by you to get this PR in, we don't have the SonarCloud Code Analysis as a requirement to merge, it's informational for the reviewer to check and assert that what it's reporting is essentially just bad config on the linux foundation infrastructure. I've checked the report and the only complaint is new uncovered code outside of the actions and reducers.

**Comment by skurnevich** [comment]
Hi Jordan, ok, I see, thank you for the explanation.

**Comment by jordanCain** [comment]
As an update, we're waiting for https://github.com/zowe/explorer-mvs/pull/122 to be approved by the CI/CD team at which point we should be able to get PR builds like this through

**Comment by jordanCain** [comment]
@skurnevich The build is failing due to linting issues now, as part of merging in one other change it seems with thisPR there would be two componenteDidUpdate functions within WebContent/js/containers/DatasetTree.js . I have created https://github.com/zowe/explorer-mvs/tree/users/jordan/fix-bad-merge to resolve the issue, please merge those changes into your branch and then we should have a green build again

**Comment by skurnevich** [comment]
@jordanCain Hi, I have merged your branch, and build seems to be fine now, thanks!

**Pull request merged**
