### PR TITLE
dsorg check to startsWith,  detect extended PS, PO

### PR DESCRIPTION
**Pull request by NakulManchanda**
Signed-off-by: Nakul Manchanda <nakul.manchanda@ibm.com>

https://github.com/zowe/explorer-mvs/issues/92

Bug fix for pulling content for extended PS-*

### CODE REVIEW

**Comment by NakulManchanda** [comment]
Did some manual testing with help of Naya, verified /content call and content itself

image

**Comment by VitekVlcek-Broadcom** [comment]
@NakulManchanda  any  idea how could I test it?
```
git clone git@github.com:zowe/explorer-mvs.git
cd explorer-mvs
npm config set registry https://gizaartifactory.jfrog.io/gizaartifactory/api/npm/npm-release/
npm login    (provide same password like in zowe artifactory gizaartifactory.jfrog.io)
npm install
npm run prod
./.pax/prepare-workspace.sh
node .pax/ascii/server/src/index.js --config .pax/ascii/server/configs/config.json --service example --path /ui/v1 --port  8080 -x /mnt/c/temp/vlcvi01/server.p12 -w password
```
Then I get `Unable to Authenticate` in browser, I guess I have to run it behind API ML. What and where should I copy to.

**Comment by NakulManchanda** [comment]
Hi @VitekVlcek-Broadcom , 

These can help you run this on your local windows/mac client
Two steps:
1)   close all chrome instances and launch from command prompt using this command
```
$ cd /c/Program Files (x86)/Google/Chrome/Application
$  ./chrome.exe --disable-web-security --user-data-dir
```

2)  File - WebContent\js\utilities\urlUtils.js, replace host
let host = 'my.mainframe.com:7554';

then use `npm run dev` from root folder, same as one containing package.json

Access url - `http://localhost:8080/`

**Comment by VitekVlcek-Broadcom** [comment]
Works on my PC as well. Thank you @NakulManchanda

**Pull request merged**
