### PR TITLE
Remove encoreUriComponent as not necessary for datasets

### PR DESCRIPTION
**Pull request by jordanCain**
Signed-off-by: Jordan Cain <jordan.cain1@uk.ibm.com>

This PR addresses Issue: [https://github.com/zowe/zlux/issues/428]

## PR Type
- [x] Bug fix
- [ ] Feature
- [ ] Other (Please indicate)

## PR Checklist
- [x] PR completes `npm run preCommit` without error
- [ ] Relevant Test cases have been added (Unit and or FVT)
- [x] Relevant update to CHANGELOG.md
- [ ] PR from forked repo? Ensure Allow edits by maintaners is set.

### CODE REVIEW

**Comment by jordanCain** [comment]
Resolves: https://github.com/zowe/zlux/issues/428

**Comment by NakulManchanda** [comment]
https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zosmfcore.multisysplex.help.doc/izuG00hpzOSNamingConventions.html

alphanumeric characters (A-Z, a-z, and 0-9), special characters ($ # @), and hyphens. The first character of each qualifier must be an alphabetic or special character. The data set name cannot contain leading or trailing periods. 

Tried these :
special characters ($ # @), and hyphens

$, @ - works for all PUT, POST & DELETE
# - don't work for PUT, POST, DELETE(couldn't try)
- (hyphen) - work for POST
                     Fails for - PUT, DELETE - basically don't like hyphen in url


Fail (s)

Hyphen - Fails when in url
PUT https://tvt5003.svl.ibm.com:7554/api/v2/datasets/NAKUL.ABC-DEG(DEF-GHI)/content
DELETE https://tvt5003.svl.ibm.com:7554/api/v2/datasets/NAKUL.ABC-DEG

# fails for both POST and PUT
PUT https://tvt5003.svl.ibm.com:7554/api/v2/datasets/NAKUL.ABC-DEG(DEF#GHI)/content
POST https://tvt5003.svl.ibm.com:7554/api/v2/datasets
{
"name":"NAKUL.ABC-DEG(DEF#GHI)"
}

**Comment by travatine** [comment]
Hi,
Please, which version of zowe is this fix shiping in?

Thanks,

Travis Thorne.

**Comment by jordanCain** [comment]
@travatine This issue was closed as it was not deem'd to be the fault of the mvs explorer but in fact is an issue with the API gateway, see this issue https://github.com/zowe/api-layer/issues/716 . There is unfortunately no confirmed fix date. If this issue is blocking you please can you comment on the api-layer issue so it can be prioritised correctly.

**Comment by travatine** [comment]
Thanks I've put a comment on that bug.

**Pull request closed without merging**
